# Generated by Django 2.2.8 on 2021-11-03 08:49

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleHealthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_token', models.CharField(default=main.models.generate_endpoint_token, max_length=36, unique=True)),
                ('oh_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember')),
            ],
        ),
        migrations.DeleteModel(
            name='OverlandUser',
        ),
    ]
